### ISSUE TITLE
ReferenceError: TLog is not defined

### ISSUE THREAD

**Issue by jamesdwilson** [superstringsoftware/observatory#25]
$ node --version
`v0.10.15`
$ meteor --version
`Release 0.6.5`
/src/lib/helpers/logging.coffee

  `@TLogger = TLog.getLogger(TLog.LOGLEVEL_MAX,true,true)`

`W20130823-11:40:05.178(-5)? (STDERR) /home/james/.meteor/tools/4010e5731d/lib/node_modules/fibers/future.js:173
W20130823-11:40:05.178(-5)? (STDERR)                        throw(ex);
W20130823-11:40:05.179(-5)? (STDERR)                              ^
W20130823-11:40:05.181(-5)? (STDERR) ReferenceError: TLog is not defined
W20130823-11:40:05.182(-5)? (STDERR)     at lib/helpers/logging.coffee:2:13
W20130823-11:40:05.182(-5)? (STDERR)     at mains (/home/james/projects/autocontent/src/.meteor/local/build/programs/server/boot.js:157:61)
W20130823-11:40:05.182(-5)? (STDERR)     at Array.forEach (native)
W20130823-11:40:05.182(-5)? (STDERR)     at Function._.each._.forEach (/home/james/.meteor/tools/4010e5731d/lib/node_modules/underscore/underscore.js:79:11)
W20130823-11:40:05.184(-5)? (STDERR)     at /home/james/projects/autocontent/src/.meteor/local/build/programs/server/boot.js:157:5`

**Comment by jamesdwilson** [comment]
My error. :)
